import { type NextPage } from "next";
import Head from "next/head";
import Login from "~/components/Login";
import { openContextModal } from "@mantine/modals";
import TodoList from "~/components/TodoList";
import Navbar from "~/components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>TodoList T3 Stack</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto my-12 max-w-3xl">
        <Navbar />
        <TodoList />
      </main>
    </>
  );
};

export default Home;
